#!/usr/bin/env zsh
# =============================================================================
# test_bundle.zsh — Split-source layout invariants
# =============================================================================
# Description:  Guards the contract between a split module's parts and the
#               single file generated from them: the root module must be
#               exactly what bin/zbundle produces from lib/<module>/, the
#               manifest must name every part and nothing else, and sourcing
#               the development loader must leave the shell in the same state
#               as sourcing the generated module.
#
#               The drift check is the important one — the root file is a
#               build artifact, and an edit made there instead of in a part
#               is silently lost on the next bundle.
#
# Usage:        zsh tests/run_tests.zsh integration
#               zsh tests/integration/test_bundle.zsh   # standalone
#
# Covers:       bin/zbundle, lib/z/parts, lib/z/z.zsh
#
# Requires:     tests/bootstrap.zsh — for ZCORE_ROOT and ztest::child_prelude.
#               No module is loaded in-process: every check either reads a
#               file or runs a clean child shell.
# =============================================================================

source "${0:A:h}/../bootstrap.zsh"

# -----------------------------------------------------------------------------
# Helpers
# -----------------------------------------------------------------------------

# _zbundle_api <entry-point>
# Print the sorted public and private function names defined by sourcing
# <entry-point> in a clean shell, one per line. The prerequisites are loaded
# first, but never `z` itself — that is what <entry-point> provides.
_zbundle_api() {
  ztest::child_prelude ui zkv zbus
  zsh -f -c "
    $REPLY
    source $1
    print -l \${(ok)functions[(I)z::*]} \${(ok)functions[(I)__z::*]}
  " 2>/dev/null
}

# _zbundle_manifest_parts
# Print the part file names listed in lib/z/parts, in manifest order.
_zbundle_manifest_parts() {
  local line
  while IFS= read -r line; do
    [[ $line == '#'* ]] && continue
    [[ -z ${line//[[:space:]]/} ]] && continue
    print -r -- "${line%%[[:space:]]*}"
  done < "${ZCORE_ROOT}/lib/z/parts"
}

# -----------------------------------------------------------------------------
# Generated output matches the parts
# -----------------------------------------------------------------------------
# These tests never regenerate the root module: rewriting it here would mask
# exactly the drift the first test exists to catch.

# The root module is generated. If it no longer matches its parts, someone
# edited the artifact — the next `make bundle` would discard that work.
test_bundle_root_module_matches_its_parts() {
  ztest::assert::returns 0 \
    zsh "${ZCORE_ROOT}/bin/zbundle" --check z
}

# A generated file has to say so, or the next reader edits it by mistake.
test_bundle_marks_the_root_module_as_generated() {
  local -a marker
  marker=( ${(f)"$(<${ZCORE_ROOT}/z)"} )
  ztest::assert::contains "${marker[*]}" 'Generated by bin/zbundle'
}

# -----------------------------------------------------------------------------
# Manifest integrity
# -----------------------------------------------------------------------------

# Every part on disk must be listed, and every listed part must exist —
# an orphaned part file is code that silently never ships.
test_bundle_manifest_covers_every_part() {
  local dir="${ZCORE_ROOT}/lib/z"
  local -a listed on_disk
  listed=( ${(f)"$(_zbundle_manifest_parts)"} )

  # z.zsh is the development loader, not a part of the bundle.
  on_disk=( ${(f)"$(cd "$dir" && print -l *.zsh)"} )
  on_disk=( ${on_disk:#z.zsh} )

  # (@o) rather than (o): without the @ the sort flag is dropped when the
  # result is immediately joined, and the comparison silently degrades into
  # "manifest order equals readdir order".
  ztest::assert::eq "${(j: :)${(@o)on_disk}}" "${(j: :)${(@o)listed}}"
}

test_bundle_manifest_parts_all_exist() {
  local dir="${ZCORE_ROOT}/lib/z"
  local part
  for part in ${(f)"$(_zbundle_manifest_parts)"}; do
    ztest::assert::file_exists "${dir}/${part}"
  done
}

# The head part carries the module banner, so it must come first.
test_bundle_manifest_starts_with_the_head_part() {
  local -a listed
  listed=( ${(f)"$(_zbundle_manifest_parts)"} )
  ztest::assert::eq 'header.zsh' "${listed[1]}"
}

# -----------------------------------------------------------------------------
# Loader and bundle equivalence
# -----------------------------------------------------------------------------

# Both entry points must define the same API. A part left out of the manifest,
# or ordered wrongly, shows up here as a missing or misdefined function.
test_bundle_loader_defines_the_same_functions_as_the_bundle() {
  local from_bundle from_loader
  from_bundle="$(_zbundle_api "${ZCORE_ROOT}/z")"
  from_loader="$(_zbundle_api "${ZCORE_ROOT}/lib/z/z.zsh")"

  [[ -n $from_bundle ]] || ztest::fail 'sourcing the bundled module defined no z:: functions'
  ztest::assert::eq "$from_bundle" "$from_loader"
}

# The load guard has to hold for the loader too: sourcing it twice must not
# fail on the readonly ZCORE_VERSION.
test_bundle_loader_is_idempotent() {
  local out
  ztest::child_prelude ui zkv
  out="$(zsh -f -c "
    $REPLY
    source ${ZCORE_ROOT}/lib/z/z.zsh
    source ${ZCORE_ROOT}/lib/z/z.zsh
    print ok
  " 2>&1 | tail -1)"
  ztest::assert::eq 'ok' "$out"
}

# Standalone execution; under the runner ztest::run is called by the runner.
(( ${ZTEST_RUNNER:-0} )) || ztest::run "${1:-test_*}"
